backend:
  name: git-gateway
  branch: master

media_folder: content/uploads
public_folder: content/uploads

locale: it

collections:
  - name: 'carousel'
    label: 'Home Carousel'
    create: false
    files:
      - name: 'home-carousel'
        label: 'Home Carousel'
        file: 'content/home/carousel.json'
        fields:
          - name: 'carousel'
            label: 'Carousel'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'image', widget: 'image', default: '../uploads/dna-banner.jpg' }

  - name: 'home-intro'
    label: 'Home Intro'
    create: false
    files:
      - name: 'home-intro'
        label: 'Home Intro'
        file: 'content/home/intro.md'
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }

  - name: 'home-sponsors'
    label: 'Home Sponsors'
    create: false
    files:
      - name: 'home-sponsors'
        label: 'Home Sponsors'
        file: 'content/home/sponsors.json'
        fields:
          - name: 'sponsors'
            label: 'Sponsors'
            widget: 'list'
            fields:
            - { label: 'Logo', name: 'logo', widget: 'image' }

  - name: 'equipment-intro'
    label: 'Equipment Intro'
    create: false
    files:
      - name: 'equipment-intro'
        label: 'Equipment Intro'
        file: 'content/equipment/intro.md'
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }

  - name: 'equipment'
    label: 'Equipment'
    create: true
    folder: 'content/equipment/items'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Order', name: 'order', widget: 'number' }
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: '../uploads/dna-image.jpg' }
      - { label: 'Text', name: 'body', widget: 'markdown' }

  - name: 'access'
    label: 'Access'
    create: false
    files:
      - name: 'access'
        label: 'Access'
        file: 'content/access/access.md'
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }

  - name: 'guidelines'
    label: 'Guidelines'
    create: false
    files:
      - name: 'guidelines'
        label: 'Guidelines'
        file: 'content/guidelines/guidelines.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Text', name: 'body', widget: 'markdown' }


  - name: 'news'
    label: 'News'
    folder: 'content/news/news'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: '../uploads/dna-image.jpg' }
      - { label: 'Date', name: 'date', widget: 'date', format: 'YYYY-MM-DD', default: '' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'events'
    label: 'Events'
    folder: 'content/news/events'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: '../uploads/dna-image.jpg' }
      - { label: 'Date', name: 'date', widget: 'date', format: 'YYYY-MM-DD', default: '' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'tutorials'
    label: 'Tutorials'
    folder: 'content/tutorials'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link to video', name: 'videoLink', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }

  - name: 'contacts'
    label: 'Contacts'
    create: false
    files:
      - name: 'contacts'
        label: 'Contacts'
        file: 'content/contacts/contacts.md'
        fields:
          - { label: 'Text (format contacts as a list, emails as BOLD)', name: 'body', widget: 'markdown' }

  - name: 'members'
    label: 'Members'
    create: false
    files:
      - name: 'members'
        label: 'Members'
        file: 'content/home/members.json'
        fields:
          - name: 'members'
            label: 'Members'
            widget: 'list'
            fields:
            - { label: 'Name', name: 'name', widget: 'string' }
            - { label: 'Mail', name: 'mail', widget: 'string' }
            - { label: 'Image', name: 'featuredImage', widget: 'image', default: '../uploads/dna-image.jpg' }

  - name: 'publications'
    label: 'Publications'
    create: true
    folder: 'content/publications'
    fields:
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Authors', name: 'authors', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Notes', name: 'notes', widget: 'string' }
      - { label: 'URL', name: 'url', widget: 'string' }

  - name: 'partners-academic'
    label: 'Academic Partners'
    create: true
    folder: 'content/partners/academic'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Order', name: 'order', widget: 'number', default: 0 }
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: null}
      - { label: 'Text', name: 'body', widget: 'markdown' }

  - name: 'partners-industrial'
    label: 'Industrial Partners'
    create: true
    folder: 'content/partners/industrial'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Partner Id', name: 'id', widget: 'string' }
      - { label: 'Order', name: 'order', widget: 'number', default: 0 }
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: null}
      - { label: 'Text', name: 'body', widget: 'markdown' }

  - name: 'partners-events'
    label: 'Partner Events'
    create: true
    folder: 'content/partners/events'
    fields:
      - { label: 'Partner Id', name: 'partnerId', widget: 'string' }
      - { label: 'File Attachment', name: 'pdf', widget: 'file', default: null }
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: '../uploads/dna-image.jpg' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
