backend:
  name: git-gateway
  branch: master

media_folder: content/uploads
public_folder: content/uploads

locale: it

collections:
  - name: 'carousel'
    label: 'Home Carousel'
    folder: 'content/carousel'
    create: true
    # slug: 'index'
    fields:
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: 'dna-banner.jpg' }
  - name: 'news'
    label: 'News'
    folder: 'content/news'
    create: true
    # slug: 'index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: 'news-img-1.jpg' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
