backend:
  name: git-gateway
  branch: master

media_folder: content/uploads
public_folder: content/uploads

locale: it

collections:
  - name: 'carousel'
    label: 'Home Carousel'
    folder: 'content/carousel'
    create: true
    fields:
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: 'dna-banner.jpg' }

  - name: 'home-intro'
    label: 'Home Intro'
    create: false
    files:
      - name: 'home-intro'
        label: 'Home Intro'
        file: 'content/home/intro.md'
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }

  - name: 'access'
    label: 'Access'
    create: false
    files:
      - name: 'access'
        label: 'Access'
        file: 'content/access/access.md'
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }

  - name: 'guidelines'
    label: 'Guidelines'
    create: false
    files:
      - name: 'guidelines'
        label: 'Guidelines'
        file: 'content/guidelines/guidelines.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Text', name: 'body', widget: 'markdown' }


  - name: 'news'
    label: 'News'
    folder: 'content/news/news'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: 'news-img-1.jpg' }
      - { label: 'Date', name: 'date', widget: 'date', format: 'YYYY-MM-DD', default: '' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'events'
    label: 'Events'
    folder: 'content/news/events'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'featuredImage', widget: 'image', default: 'news-img-1.jpg' }
      - { label: 'Date', name: 'date', widget: 'date', format: 'YYYY-MM-DD', default: '' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'tutorials'
    label: 'tutorials'
    folder: 'content/tutorials'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link to video', name: 'videoLink', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }

  - name: 'contacts'
    label: 'contacts'
    create: false
    files:
      - name: 'contacts'
        label: 'Contacts'
        file: 'content/contacts/contacts.md'
        fields:
          - { label: 'Text (format contacts as a list, emails as BOLD)', name: 'body', widget: 'markdown' }

  - name: 'members'
    label: 'Members'
    create: false
    files:
      - name: 'members'
        label: 'Members'
        file: 'content/home/members.json'
        fields:
          - name: 'members'
            label: 'Members'
            widget: 'list'
            fields:
            - { label: 'Name', name: 'name', widget: 'string' }
            - { label: 'Mail', name: 'mail', widget: 'string' }
            - { label: 'Image', name: 'featuredImage', widget: 'image', default: 'news-img-1.jpg' }

  - name: 'publications'
    label: 'Publications'
    create: true
    folder: 'content/publications'
    fields:
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Authors', name: 'authors', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Notes', name: 'notes', widget: 'string' }
      - { label: 'URL', name: 'url', widget: 'string' }
